version: '3'

services:
  app:
    image: phpswoole/swoole:5.0.2-php8.2
    environment:
      AUTORELOAD_PROGRAMS: "swoole"
      AUTORELOAD_ANY_FILES: 0
    ports:
      - 80:9501
    volumes:
      - ./server:/var/www